import { getUserById } from "@/utils/userStorage";
import { makeId, readJson, writeJson } from "@/lib/localStorage";

export type ChatMessage = { id: string; conversationId: string; senderId: string; senderName: string; receiverId: string; content: string; timestamp: number; is_read: boolean; deleted: boolean };
export type Conversation = { id: string; user1Id: string; user2Id: string; createdAt: number };
export type ConversationSummary = { id: string; otherUserId: string; name: string; avatar?: string; lastMessage: string; lastTime: number; unreadCount: number };
const CONVERSATIONS_KEY = "campusprenuer_conversations";
const MESSAGES_KEY = "campusprenuer_messages";
const conversations = () => readJson<Conversation[]>(CONVERSATIONS_KEY, []);
const messages = () => readJson<ChatMessage[]>(MESSAGES_KEY, []);
export function getOrCreateConversation(userId: string, otherId: string) { const existing = conversations().find((item) => (item.user1Id === userId && item.user2Id === otherId) || (item.user1Id === otherId && item.user2Id === userId)); if (existing) return existing; const conversation = { id: makeId(), user1Id: userId, user2Id: otherId, createdAt: Date.now() }; writeJson(CONVERSATIONS_KEY, [conversation, ...conversations()]); return conversation; }
export function getMessages(conversationId: string) { return messages().filter((message) => message.conversationId === conversationId).sort((a, b) => a.timestamp - b.timestamp); }
export function sendMessage(conversationId: string, senderId: string, content: string) { const conversation = conversations().find((item) => item.id === conversationId); if (!conversation) throw new Error("Conversation not found."); const receiverId = conversation.user1Id === senderId ? conversation.user2Id : conversation.user1Id; const sender = getUserById(senderId); const message: ChatMessage = { id: makeId(), conversationId, senderId, senderName: sender?.name || "User", receiverId, content, timestamp: Date.now(), is_read: false, deleted: false }; writeJson(MESSAGES_KEY, [...messages(), message]); window.dispatchEvent(new Event("campus-chat-change")); return message; }
export function deleteMessage(id: string) { writeJson(MESSAGES_KEY, messages().map((message) => message.id === id ? { ...message, deleted: true, content: "This message was deleted" } : message)); window.dispatchEvent(new Event("campus-chat-change")); }
export function markAsRead(conversationId: string, userId: string) { writeJson(MESSAGES_KEY, messages().map((message) => message.conversationId === conversationId && message.receiverId === userId ? { ...message, is_read: true } : message)); }
export function getUserConversations(userId: string): ConversationSummary[] { return conversations().filter((conversation) => conversation.user1Id === userId || conversation.user2Id === userId).map((conversation) => { const otherUserId = conversation.user1Id === userId ? conversation.user2Id : conversation.user1Id; const other = getUserById(otherUserId); const ownMessages = getMessages(conversation.id); const last = ownMessages.at(-1); return { id: conversation.id, otherUserId, name: other?.name || "User", avatar: other?.avatar_url, lastMessage: last?.deleted ? "This message was deleted" : last?.content || "", lastTime: last?.timestamp || conversation.createdAt, unreadCount: ownMessages.filter((message) => message.receiverId === userId && !message.is_read).length }; }).sort((a, b) => b.lastTime - a.lastTime); }
export function getUnreadCount(userId: string) { return getUserConversations(userId).reduce((sum, conversation) => sum + conversation.unreadCount, 0); }
